# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [409]:
# Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [410]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv("./Resources/applicants_data.csv")

# Review the DataFrame
applicant_data_df.head(5)

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [411]:
# Review the data types associated with the columns
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [412]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(['EIN','NAME'], axis=1)

# Review the DataFrame
applicant_data_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [414]:
# Create a list of categorical variables 
categorical_variables = pd.Categorical(applicant_data_df)
categorical_variables = pd.array(categorical_variables).reshape(-1, 1)

# Display the categorical variables list
categorical_variables

[['APPLICATION_TYPE'], ['AFFILIATION'], ['CLASSIFICATION'], ['USE_CASE'], ['ORGANIZATION'], ['STATUS'], ['INCOME_AMT'], ['SPECIAL_CONSIDERATIONS'], ['ASK_AMT'], ['IS_SUCCESSFUL']]
Categories (10, object): ['AFFILIATION', 'APPLICATION_TYPE', 'ASK_AMT', 'CLASSIFICATION', ..., 'ORGANIZATION', 'SPECIAL_CONSIDERATIONS', 'STATUS', 'USE_CASE']

In [415]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [416]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(categorical_variables)

encoded_data

c:\Users\Eyasu\Anaconda3\envs\RC\lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]])

In [417]:
# Create a DataFrame with the encoded variables

encoded_df = pd.DataFrame(encoded_data, columns=enc.get_feature_names_out())
# Review the DataFrame
encoded_df

,x0_AFFILIATION,x0_APPLICATION_TYPE,x0_ASK_AMT,x0_CLASSIFICATION,x0_INCOME_AMT,x0_IS_SUCCESSFUL,x0_ORGANIZATION,x0_SPECIAL_CONSIDERATIONS,x0_STATUS,x0_USE_CASE
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
6,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [418]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
encoded1_df = pd.concat([applicant_data_df,encoded_df], axis=1)

# Review the Dataframe
encoded1_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL,x0_AFFILIATION,x0_APPLICATION_TYPE,x0_ASK_AMT,x0_CLASSIFICATION,x0_INCOME_AMT,x0_IS_SUCCESSFUL,x0_ORGANIZATION,x0_SPECIAL_CONSIDERATIONS,x0_STATUS,x0_USE_CASE
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [419]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df['x0_IS_SUCCESSFUL']

# Display a sample of y
y

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
5    0.0
6    0.0
7    0.0
8    0.0
9    1.0
Name: x0_IS_SUCCESSFUL, dtype: float64

In [420]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df.drop(columns='x0_IS_SUCCESSFUL')

# Review the features DataFrame
X

,x0_AFFILIATION,x0_APPLICATION_TYPE,x0_ASK_AMT,x0_CLASSIFICATION,x0_INCOME_AMT,x0_ORGANIZATION,x0_SPECIAL_CONSIDERATIONS,x0_STATUS,x0_USE_CASE
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
6,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Step 6: Split the features and target sets into training and testing datasets.

In [421]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [422]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
# X_scaler = scaler.fit(X_train)
scaler = StandardScaler().fit(X_test)


# Fit the scaler to the features training dataset
# X_train_scaled = X_scaler.transform(X_train)
# X_test_scaled = X_scaler.transform(X_test)

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [437]:
# Define the the number of inputs (features) to the model
number_input_features = 9

# Review the number of features
number_input_features

9

In [438]:
# Define the number of neurons in the output layer
number_output_neurons = 2

In [439]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 =  6

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

6

In [440]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  4

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

4

In [441]:
# Create the Sequential model instance
nn = Sequential()

In [442]:
# Add the first hidden layer


nn.add(
    Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)
# nn.add(Dense(units=hidden_nodes_layer1, activation="relu", input_dim=number_input_features, name = 'layer11'))

In [443]:
# Add the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2, activation="relu"))
# nn.add(Dense(units=hidden_nodes_layer2, activation="relu", input_dim=number_input_features, name = 'layer12'))

In [444]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=1, activation="linear"))
# nn.add(Dense(units=number_output_neurons, activation="sigmoid"))

In [445]:
# Display the Sequential model summary
nn.summary()

Model: "sequential_14"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_12 (Dense)            (None, 6)                 60

 dense_13 (Dense)            (None, 4)                 28

 dense_14 (Dense)            (None, 1)                 5

=================================================================
Total params: 93
Trainable params: 93
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [446]:
# Compile the Sequential model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [447]:
# Fit the model using 50 epochs and the training data
nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
1/1 [==============================] - 1s 1s/step - loss: 0.0584 - accuracy: 1.0000
Epoch 2/50
1/1 [==============================] - 0s 12ms/step - loss: 0.0556 - accuracy: 1.0000
Epoch 3/50
1/1 [==============================] - 0s 13ms/step - loss: 0.0527 - accuracy: 1.0000
Epoch 4/50
1/1 [==============================] - 0s 22ms/step - loss: 0.0506 - accuracy: 1.0000
Epoch 5/50
1/1 [==============================] - 0s 8ms/step - loss: 0.0486 - accuracy: 1.0000
Epoch 6/50
1/1 [==============================] - 0s 17ms/step - loss: 0.0465 - accuracy: 1.0000
Epoch 7/50
1/1 [==============================] - 0s 9ms/step - loss: 0.0445 - accuracy: 1.0000
Epoch 8/50
1/1 [==============================] - 0s 8ms/step - loss: 0.0425 - accuracy: 1.0000
Epoch 9/50
1/1 [==============================] - 0s 13ms/step - loss: 0.0406 - accuracy: 1.0000
Epoch 10/50
1/1 [==============================] - 0s 7ms/step - loss: 0.0387 - accuracy: 1.0000
Epoch 11/50
1/1 [==============================] - 0s 13ms/step - loss: 0.0367 - accuracy: 1.0000
Epoch 12/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0349 - accuracy: 1.0000
Epoch 13/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0330 - accuracy: 1.0000
Epoch 14/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0312 - accuracy: 1.0000
Epoch 15/50
1/1 [==============================] - 0s 9ms/step - loss: 0.0294 - accuracy: 1.0000
Epoch 16/50
1/1 [==============================] - 0s 7ms/step - loss: 0.0276 - accuracy: 1.0000
Epoch 17/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0258 - accuracy: 1.0000
Epoch 18/50
1/1 [==============================] - 0s 7ms/step - loss: 0.0241 - accuracy: 1.0000
Epoch 19/50
1/1 [==============================] - 0s 18ms/step - loss: 0.0223 - accuracy: 1.0000
Epoch 20/50
1/1 [==============================] - 0s 9ms/step - loss: 0.0206 - accuracy: 1.0000
Epoch 21/50
1/1 [==============================] - 0s 9ms/step - loss: 0.0190 - accuracy: 1.0000
Epoch 22/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0173 - accuracy: 1.0000
Epoch 23/50
1/1 [==============================] - 0s 10ms/step - loss: 0.0156 - accuracy: 1.0000
Epoch 24/50
1/1 [==============================] - 0s 0s/step - loss: 0.0139 - accuracy: 1.0000
Epoch 25/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0122 - accuracy: 1.0000
Epoch 26/50
1/1 [==============================] - 0s 5ms/step - loss: 0.0106 - accuracy: 1.0000
Epoch 27/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0089 - accuracy: 1.0000
Epoch 28/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0078 - accuracy: 1.0000
Epoch 29/50
1/1 [==============================] - 0s 12ms/step - loss: 0.0068 - accuracy: 1.0000
Epoch 30/50
1/1 [==============================] - 0s 5ms/step - loss: 0.0058 - accuracy: 1.0000
Epoch 31/50
1/1 [==============================] - 0s 5ms/step - loss: 0.0048 - accuracy: 1.0000
Epoch 32/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0038 - accuracy: 1.0000
Epoch 33/50
1/1 [==============================] - 0s 5ms/step - loss: 0.0029 - accuracy: 1.0000
Epoch 34/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0020 - accuracy: 1.0000
Epoch 35/50
1/1 [==============================] - 0s 5ms/step - loss: 0.0011 - accuracy: 1.0000
Epoch 36/50
1/1 [==============================] - 0s 11ms/step - loss: 1.6933e-04 - accuracy: 1.0000
Epoch 37/50
1/1 [==============================] - 0s 10ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 38/50
1/1 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 39/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 40/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 41/50
1/1 [==============================] - 0s 9ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 42/50
1/1 [==============================] - 0s 9ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 43/50
1/1 [==============================] - 0s 16ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 44/50
1/1 [==============================] - 0s 8ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 45/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 46/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 47/50
1/1 [==============================] - 0s 7ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 48/50
1/1 [==============================] - 0s 0s/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 49/50
1/1 [==============================] - 0s 19ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 50/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0000e+00 - accuracy: 1.0000

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [448]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy =  nn.evaluate(
    X_test_scaled, y_test, verbose=2
)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

1/1 - 0s - loss: 5.1416 - accuracy: 0.6667 - 186ms/epoch - 186ms/step
Loss: 5.1416497230529785, Accuracy: 0.6666666865348816

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [568]:
# Set the model's file path
file_path = "./Resources/AlphabetSoup.h5"

# Export your model to a HDF5 file
nn.save_weights(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [538]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

9

In [540]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 21

In [541]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = 5

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

5

In [542]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [543]:
# First hidden layer
nn_A1.add(
    Dense(units=hidden_nodes_layer1_A1, input_dim=number_input_features, activation="relu")
)


# Output layer
nn_A1.add(Dense(units=1, activation="linear"))


# Check the structure of the model
nn_A1.summary()

Model: "sequential_23"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_33 (Dense)            (None, 5)                 50

 dense_34 (Dense)            (None, 1)                 6

=================================================================
Total params: 56
Trainable params: 56
Non-trainable params: 0
_________________________________________________________________

In [544]:
# Compile the Sequential model
nn_A1.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [545]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50

1/1 [==============================] - 1s 675ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 2/50
1/1 [==============================] - 0s 8ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 3/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 4/50
1/1 [==============================] - 0s 10ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 5/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 6/50
1/1 [==============================] - 0s 8ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 7/50
1/1 [==============================] - 0s 12ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 8/50
1/1 [==============================] - 0s 7ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 9/50
1/1 [==============================] - 0s 7ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 10/50
1/1 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 11/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 12/50
1/1 [==============================] - 0s 9ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 13/50
1/1 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 14/50
1/1 [==============================] - 0s 7ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 15/50
1/1 [==============================] - 0s 10ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 16/50
1/1 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 17/50
1/1 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 18/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 19/50
1/1 [==============================] - 0s 12ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 20/50
1/1 [==============================] - 0s 12ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 21/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 22/50
1/1 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 23/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 24/50
1/1 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 25/50
1/1 [==============================] - 0s 37ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 26/50
1/1 [==============================] - 0s 12ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 27/50
1/1 [==============================] - 0s 9ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 28/50
1/1 [==============================] - 0s 17ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 29/50
1/1 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 30/50
1/1 [==============================] - 0s 83ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 31/50
1/1 [==============================] - 0s 16ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 32/50
1/1 [==============================] - 0s 8ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 33/50
1/1 [==============================] - 0s 27ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 34/50
1/1 [==============================] - 0s 30ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 35/50
1/1 [==============================] - 0s 9ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 36/50
1/1 [==============================] - 0s 10ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 37/50
1/1 [==============================] - 0s 0s/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 38/50
1/1 [==============================] - 0s 22ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 39/50
1/1 [==============================] - 0s 9ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 40/50
1/1 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 41/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 42/50
1/1 [==============================] - 0s 10ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 43/50
1/1 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 44/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 45/50
1/1 [==============================] - 0s 12ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 46/50
1/1 [==============================] - 0s 9ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 47/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 48/50
1/1 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 49/50
1/1 [==============================] - 0s 8ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 50/50
1/1 [==============================] - 0s 7ms/step - loss: 0.0000e+00 - accuracy: 1.0000

#### Alternative Model 2

In [558]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[1])

# Review the number of features
number_input_features

9

In [559]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 1

In [560]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = 1

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

1

In [561]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [562]:
# First hidden layer
nn_A2.add(
    Dense(units=hidden_nodes_layer1_A2, input_dim=number_input_features, activation="relu")
)
# Output layer
nn_A2.add(Dense(units=1, activation="linear"))

# Check the structure of the model
nn_A2.summary()

Model: "sequential_25"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_37 (Dense)            (None, 1)                 10

 dense_38 (Dense)            (None, 1)                 2

=================================================================
Total params: 12
Trainable params: 12
Non-trainable params: 0
_________________________________________________________________

In [563]:
# Compile the model
nn_A2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [564]:
# Fit the model
fit_model_A2 = nn_A2.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
1/1 [==============================] - 1s 822ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 2/50
1/1 [==============================] - 0s 8ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 3/50
1/1 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 4/50
1/1 [==============================] - 0s 8ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 5/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 6/50
1/1 [==============================] - 0s 4ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 7/50
1/1 [==============================] - 0s 11ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 8/50
1/1 [==============================] - 0s 11ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 9/50
1/1 [==============================] - 0s 10ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 10/50
1/1 [==============================] - 0s 9ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 11/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 12/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 13/50
1/1 [==============================] - 0s 8ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 14/50
1/1 [==============================] - 0s 10ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 15/50
1/1 [==============================] - 0s 8ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 16/50
1/1 [==============================] - 0s 7ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 17/50
1/1 [==============================] - 0s 9ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 18/50
1/1 [==============================] - 0s 9ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 19/50
1/1 [==============================] - 0s 10ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 20/50
1/1 [==============================] - 0s 8ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 21/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 22/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 23/50
1/1 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 24/50
1/1 [==============================] - 0s 14ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 25/50
1/1 [==============================] - 0s 7ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 26/50
1/1 [==============================] - 0s 10ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 27/50
1/1 [==============================] - 0s 13ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 28/50
1/1 [==============================] - 0s 9ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 29/50
1/1 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 30/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 31/50
1/1 [==============================] - 0s 13ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 32/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 33/50
1/1 [==============================] - 0s 10ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 34/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 35/50
1/1 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 36/50
1/1 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 37/50
1/1 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 38/50
1/1 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 39/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 40/50
1/1 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 41/50
1/1 [==============================] - 0s 17ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 42/50
1/1 [==============================] - 0s 6ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 43/50
1/1 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 44/50
1/1 [==============================] - 0s 7ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 45/50
1/1 [==============================] - 0s 0s/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 46/50
1/1 [==============================] - 0s 4ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 47/50
1/1 [==============================] - 0s 4ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 48/50
1/1 [==============================] - 0s 5ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 49/50
1/1 [==============================] - 0s 7ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 50/50
1/1 [==============================] - 0s 9ms/step - loss: 0.0000e+00 - accuracy: 1.0000

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [547]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy =  nn.evaluate(
    X_test_scaled, y_test, verbose=2
)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
1/1 - 0s - loss: 5.1416 - accuracy: 0.6667 - 43ms/epoch - 43ms/step
Loss: 5.1416497230529785, Accuracy: 0.6666666865348816

In [548]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy =  nn_A1.evaluate(
    X_test_scaled, y_test, verbose=2
)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
1/1 - 0s - loss: 5.1416 - accuracy: 0.6667 - 35ms/epoch - 35ms/step

Loss: 5.1416497230529785, Accuracy: 0.6666666865348816

In [565]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss2, model_accuracy2 =  nn_A2.evaluate(
    X_test_scaled, y_test, verbose=2
)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
WARNING:tensorflow:5 out of the last 11 calls to <function Model.make_test_function.<locals>.test_function at 0x00000194902755A0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
1/1 - 0s - loss: 5.1416 - accuracy: 0.6667 - 248ms/epoch - 248ms/step
Loss: 5.1416497230529785, Accuracy: 0.6666666865348816

### Step 3: Save each of your alternative models as an HDF5 file.

In [566]:
# Set the file path for the first alternative model
file_path = "./Resources/alternative_1.h5"

# Export your model to a HDF5 file
nn_A1.save_weights(file_path)

In [567]:
# Set the file path for the second alternative model
file_path = "./Resources/alternative_2.h5"

# Export your model to a HDF5 file
nn_A1.save_weights(file_path)